
spring:
  application:
    name: course-service
    version: 1.0.0

  datasource:
    url: jdbc:postgresql://localhost:5432/course
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
